### ISSUE TITLE
SPDXLicenseRemovePlugin doesn't remove '\\' from the license

### ISSUE THREAD

**Issue by Aniket-Engg** [RyuuGan/sol-merger#44] opened 2020-12-09 08:19 UTC

**Comment by RyuuGan** [comment] 2022-02-22 20:17
Closing this issue for now, since it is hard to reproduce it.

Feel free to reopen it with the example of the contract to reproduce.

Best regards,
Valerii Aligorskii

**Closed as completed by RyuuGan** 2022-02-22 20:17 UTC
